# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PlayerKitDemo' do

pod 'PlayerKit', :path => '../'

pod 'AFNetworking'
pod 'Mantle'
pod 'PINRemoteImage'

end

target 'PlayerKitDemoTests' do

end

target 'PlayerKitDemoUITests' do

end

